name: latex build
on: [push]
jobs:
  build-tex-files:
    runs-on: ubuntu-latest
    container: raabf/latex-versions:texlive2020
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: make CI=1 resume cover
